channels:
  - defaults
  - conda-forge
dependencies:
  - conda-forge::hdmf>=3.11.0, <4.0.0
  - ipykernel
  - pip:
    - pynwb>=2.5.0, <3.0.0
    - pynapple>=0.5.0, <0.6.0
    - remfile>=0.1.10, <0.2.0
    - dendro>=0.1.30, <0.2.0
    - figurl>=0.2.22, <0.3.0