name: Build cebra1 image and push to GCR

on:
  push:
    branches:
      - main
    paths:
      - "apps/cebra1/**"
  workflow_dispatch:

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          NAME="cebra1" && \
          docker buildx build --push \
          -t ghcr.io/magland/$NAME:latest \
          --cache-to type=inline \
          --cache-from type=registry,ref=ghcr.io/magland/$NAME:latest \
          -f ./apps/$NAME/Dockerfile .
